export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'

export const DELETE_SELECTED_DAY_TASKS = 'DELETE_SELECTED_DAY_TASKS'
export const DELETE_ALL_TASKS = 'DELETE_ALL_TASKS'

export const CHANGE_SELECTED_DAY = 'CHANGE_SELECTED_DAY'
